export type ClientActionName =
    | 'getSamples'
    | 'getSamplesWithTab'
    | 'getSamplesForApprovalCount'
    | 'assignTests'
    | 'updateSample'
    | 'createSample'
    | 'accessionAndAssignTests'
    | 'recordSampleLabelPrint'
    | 'getSampleTests'
    | 'getResultsBySample'
    | 'getSampleSubmissionReview'
    | 'saveBatchResults'
    | 'submitSampleForReview'
    | 'getAssayDefinitions'
    | 'getMethods'
    | 'getMethodNameSuggestions'
    | 'addMethodToAssay'
    | 'setDefaultMethod'
    | 'removeMethodFromAssay'
    | 'createAssayDefinition'
    | 'updateAssayDefinition'
    | 'deleteAssayDefinition'
    | 'getAssaySampleTypeCatalogManager'
    | 'getPublishedAssaySampleTypeCatalog'
    | 'cloneAssaySampleTypeCatalogRevision'
    | 'updateAssaySampleTypeCatalogReview'
    | 'reviewAssaySampleTypeCatalogRevision'
    | 'publishAssaySampleTypeCatalogRevision'
    | 'approveResults'
    | 'cancelApproval'
    | 'createUser'
    | 'updateUser'
    | 'deleteUser'
    | 'configureManagerOtpEmail'
    | 'getMaskedManagerOtpEmail'
    | 'rejectSample'
    | 'discardSample'
    | 'getRejectedSamplesCount'
    | 'upsertClient'
    | 'findClientByIdentity'
    | 'getClient'
    | 'getClients'
    | 'updateClient'
    | 'uploadManagerSignature'    // @deprecated - use uploadSignature
    | 'uploadSignature'           // New generic action for both roles
    | 'getActiveSignature'
    | 'getSignatureHistory'
    | 'downloadSignature'
    | 'searchSamples'
    | 'searchClients'
    | 'searchAssays'
    | 'searchResults'
    | 'searchAuditLogs'
    | 'globalSearch'
    | 'generateCoA'
    | 'regenerateCoA'

export interface ClientActionRequest {
    action: ClientActionName
    payload?: unknown
}
